
// Note: this file is auto-generated by meta_join.js. Don't Modify me !
YUI().use(function(Y) {

	/**
 	* YUI 3 module metadata
 	* @module scratch-for-web-loader
	 */
	var CONFIG = {
		groups: {
			'clicrdv': {
				base: '/Users/michaelweiss/Programs/scratch-for-web/build/',
				combine: false,
				modules: {"scratch-block-render":{"path":"scratch-block-render/scratch-block-render.js","requires":["base","view","scratch-block-model","dd-plugin","dd-drop-plugin","graphics","substitute","escape","tabview"],"skinnable":true},"scratch-block-model":{"path":"scratch-block-model/scratch-block-model.js","requires":["widget","intl","model","model-list","node-screen"],"skinnable":true}}
			}
		}
	};

	if(typeof YUI_config === 'undefined') { YUI_config = {groups:{}}; }
	Y.mix(YUI_config.groups, CONFIG.groups);

});