
// Note: this file is auto-generated by meta_join.js. Don't Modify me !
YUI().use(function(Y) {

	/**
 	* YUI 3 module metadata
 	* @module scratch-for-web-loader
	 */
	var CONFIG = {
		groups: {
			'clicrdv': {
				base: '../../../build/',
				combine: false,
				modules: {}
			}
		}
	};

	if(typeof YUI_config === 'undefined') { YUI_config = {groups:{}}; }
	Y.mix(YUI_config.groups, CONFIG.groups);

});